### PR TITLE
bugfix: diagonal lines in diagram, new google api URL

### PR DESCRIPTION
**Pull request by debrunner**
Charts missing after upgrade from ubuntu 14.04 to 16.04
https://github.com/wfrog/wfrog/issues/149

### CODE REVIEW

**Comment by gak** [comment]
Thanks!

**Comment by debrunner** [comment]
Thank you for the very fast merge!

**Comment by debrunner** [comment]
Can we update upstream pip package?
https://pypi.python.org/pypi/pygooglechart

**Comment by sravfeyn** [comment]
Thanks for the fix here! Is it possible to make a Pypi release with this fix. The current version `0.4.0` doesn't contain this fix.

**Comment by debrunner** [comment]
> Thanks for the fix here! Is it possible to make a Pypi release with this fix. The current version `0.4.0` doesn't contain this fix.

# fix diagram issues by uninstalling old version and installing newest fixed version form github.com
sudo apt remove python-pygooglechart
sudo pip2 install --upgrade --force-reinstall git+https://github.com/grahamu/pygooglechart.git  # fork with fixed googlechart-URL and fix of diagram diagonal line
pip2 show pygooglechart  # check package

https://github.com/wfrog/wfrog/issues/149#issuecomment-368185821

**Pull request merged**
